# For a single document, --- is optional and has no effect on parsing but can improve clarity and consistency.

# This file contains globs for automatically adding labels based on changed files,
# for use with https://github.com/actions/labeler.
---
######################################################################
## CI
######################################################################

# "build/ci":
# - changed-files:
#   - any-glob-to-any-file:
#     - .binder/*
#     - .circleci/*
#     - .devcontainer/**/*
#     - .github/**/*
#     - .spin/*
#     - docker/**/*

# build:templates:
# - changed-files:
#   - any-glob-to-any-file:
#     - scikitplot/**/*.tp

# build:meson:
# - changed-files:
#   - any-glob-to-any-file:
#     - pyproject.toml
#     - meson.build
#     - meson.options
#     - scikitplot/**/meson.build
#     - setup.cfg

# Release:
# - changed-files:
#   - any-glob-to-any-file:
#     - docs/development/maintainers/releasing.rst
#     - .github/workflows/publish.yml

# "CI: Run wheels":
#   - changed-files:
#     - any-glob-to-any-file: ['.github/workflows/wheels.yml']

######################################################################
## Documentation
######################################################################

# DX:
# - changed-files:
#   - any-glob-to-any-file:
#     - docs/source/devel/**/*

# documentation:
# - changed-files:
#   - any-glob-to-any-file:
#     # Add 'Documentation' label to any changes within 'docs' folder or any subfolders
#     # Add 'Documentation' label to any file changes within 'docs' folder
#     - docs/**/*
#     - CITATION*
#     - LICENSE
#     - LICENSES/*
#     # Add 'Documentation' label to any change to .md files within the entire repository
#     # - '**/*.md'
#     # Add 'Documentation' label to any change to .rst files within the entire repository
#     # - '**/*.rst'
#   # - all-globs-to-any-file:
#   #   - '!CHANGES.rst'
#   #   - '!docs/changes/*'

# "doc:examples":
#   - changed-files:
#       - any-glob-to-any-file:
#           - 'galleries/**/*'

######################################################################
## Language
######################################################################

# lang:c/c++:
# - changed-files:
#   - any-glob-to-any-file:
#     - scikitplot/**/*.c
#     - scikitplot/**/*.c.in
#     - scikitplot/**/*.c.old
#     - scikitplot/**/*.h
#     - scikitplot/**/*.h.in
#     - scikitplot/**/*.cpp
#     - scikitplot/**/*.cc
#     - scikitplot/**/*.cxx
#     - scikitplot/**/*.hpp

# lang:fortran:
# - changed-files:
#   - any-glob-to-any-file:
#     - scikitplot/**/*.f
#     - scikitplot/**/*.f.src
#     - scikitplot/**/*.F
#     - scikitplot/**/*.f90
#     - scikitplot/**/*.pyf

# lang:cython:
# - changed-files:
#   - any-glob-to-any-file:
#     - scikitplot/**/*.pyx*
#     - scikitplot/**/*.pxd*
#     - scikitplot/**/*.pxi*
#     - scikitplot/**/*.pyi*
#     - scikitplot/**/_generate_pyx.py

######################################################################
## Modules
######################################################################

# "scikitplot/_astropy":
# - changed-files:
#   - any-glob-to-any-file:
#     - scikitplot/_astropy/**/*

# "scikitplot/_build_utils":
# - changed-files:
#   - any-glob-to-any-file:
#     - scikitplot/_build_utils/**/*

# "scikitplot/_compat":
# - changed-files:
#   - any-glob-to-any-file:
#     - scikitplot/_compat/**/*

# "scikitplot/_externals":
# - changed-files:
#   - any-glob-to-any-file:
#     - scikitplot/_externals/**/*

# "scikitplot/_factory_api":
# - changed-files:
#   - any-glob-to-any-file:
#     - scikitplot/_factory_api/**/*

# "scikitplot/_seaborn":
# - changed-files:
#   - any-glob-to-any-file:
#     - scikitplot/_seaborn/**/*

# "scikitplot/_tweedie":
# - changed-files:
#   - any-glob-to-any-file:
#     - scikitplot/_tweedie/**/*

# "scikitplot/_xp_core_lib":
# - changed-files:
#   - any-glob-to-any-file:
#     - scikitplot/_xp_core_lib/**/*

# "scikitplot/api":
# - changed-files:
#   - any-glob-to-any-file:
#     - scikitplot/api/**/*

# "scikitplot/experimental":
# - changed-files:
#   - any-glob-to-any-file:
#     - scikitplot/experimental/**/*

# "scikitplot/kds":
# - changed-files:
#   - any-glob-to-any-file:
#     - scikitplot/kds/**/*

# "scikitplot/modelplotpy":
# - changed-files:
#   - any-glob-to-any-file:
#     - scikitplot/modelplotpy/**/*

# "scikitplot/probscale":
# - changed-files:
#   - any-glob-to-any-file:
#     - scikitplot/probscale/**/*

# "scikitplot/stats":
# - changed-files:
#   - any-glob-to-any-file:
#     - scikitplot/stats/**/*

# "scikitplot/visualkeras":
# - changed-files:
#   - any-glob-to-any-file:
#     - scikitplot/visualkeras/**/*

# "scikitplot/sp_logging":
# - changed-files:
#   - any-glob-to-any-file:
#     - scikitplot/sp_logging/**/*

######################################################################
## Testing
######################################################################

# testing:
# - changed-files:
#   - any-glob-to-any-file:
#     - scikitplot/tests/**/*
#     - '**/conftest.py'
#     - conftest.py
#     - codecov.yml
#     - tox.ini
#     - .flake8
#     - .mypy.ini
#     - .pre-commit-config.yaml
#     - .pre-commit-hooks.yaml
#     - .ruff.toml

# installation:
# - changed-files:
#   - any-glob-to-any-file:
#     - docs/install.rst
#     - MANIFEST.in
#     - pyproject.toml
#     - setup.py

# config:
# - changed-files:
#   - any-glob-to-any-file:
#     - '**/config/**/*'
#     - scikitplot/extern/configobj/**/*

######################################################################
## dev-automation
######################################################################

# dev-automation:
# - changed-files:
#   - any-glob-to-any-file:
#     - .github/**/*
#     - .github/ISSUE_TEMPLATE/**
#     - .github/workflows/stalebot.
#     - .github/workflows/open_actions.yml
#     - .github/workflows/update_astropy_iers_data_pin.*
#     - .devcontainer/**/*
#     - .pre-commit-config.yaml
#     - .ruff.toml

######################################################################
## Topics
######################################################################

# "topic: sphinx extension":
#   - changed-files:
#       - any-glob-to-any-file:
#           - 'scikitplot/sphinxext/**/*'

# "backend: agg":
#   - changed-files:
#       - any-glob-to-any-file:
#           - 'lib/matplotlib/backends/backend_agg.py*'

# "GUI: tk":
#   - changed-files:
#       - any-glob-to-any-file:
#           - 'src/_tkagg.cpp'
#           - 'src/_tkmini.h'

# "topic: axes":
#   - changed-files:
#       - any-glob-to-any-file:
#           # Note, axes.py is not included here because it contains many plotting
#           # methods, for which changes would not be considered on topic.
#           - 'lib/matplotlib/axes/_base.py*'
