repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      # - id: end-of-file-fixer
      #   exclude_types: [svg]
      - id: mixed-line-ending
      - id: no-commit-to-branch  # Default is master and main.
      - id: trailing-whitespace
        exclude_types: [svg]
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - pydocstyle>5.1.0
          - flake8-docstrings>1.4.0
          - flake8-force
        args: ["--docstring-convention=all"]
        exclude: scikitplot/_seaborn/(cm\.py|external/)
        types: [file, python]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        args: [--follow-imports=skip]
        files: scikitplot/_seaborn/_(core|marks|stats)/
