name: Check PR Changelog

# This check makes sure that the changelog is properly updated
# when a PR introduces a change in a test file.
# To bypass this check, label the PR with "No Changelog Needed".
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

permissions:
  # only required for workflows in private repositories
  contents: read  # for actions/checkout to fetch code
  pull-requests: read

# simultaneity
concurrency:
  ## The group key defines how GitHub Actions groups workflow runs together.
  ## github.workflow → The name of the workflow file.
  ## github.ref      → The branch or tag the workflow is running on.
  group: ${{ github.workflow }}-${{ github.ref }}
  ## If you push multiple times quickly, older runs would continue even though newer ones have started.
  ## Canceling previous runs reduces resource usage and speeds up feedback.
  cancel-in-progress: true

jobs:
  check:
    name: A reviewer will let you know if it is required or can be bypassed
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout (cloned) repository with full history
      #   uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      #   with:
      #     persist-credentials: false  # Prevents accidental credential exposure
      #     # submodules: true  # Fetch Hugo themes (true OR recursive)
      #     fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # - name: Check if tests have changed
      #   id: tests_changed
      #   run: |
      #     set -xe
      #     changed_files=$(git diff --name-only origin/main)
      #     # Changelog should be updated only if tests have been modified
      #     if [[ "$changed_files" =~ tests ]]
      #     then
      #       echo "check_changelog=true" >> $GITHUB_OUTPUT
      #     fi

      - name: Check if towncrier change log entry is correct
        # if: steps.tests_changed.outputs.check_changelog == 'true'
        uses: scientific-python/action-towncrier-changelog@1d7332022f76e36fe8ce2d716b851f3f98063c62  # v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BOT_USERNAME: changelog-bot
