# https://github.com/scientific-python/action-towncrier-changelog
---
name: Check PR Changelog

# This check makes sure that the changelog is properly updated
# when a PR introduces a change in a test file.
# To bypass this check, label the PR with "No Changelog Needed".
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

permissions:
  # only required for workflows in private repositories
  contents: read  # for actions/checkout to fetch code
  pull-requests: read

# simultaneity
concurrency:
  ## The group key defines how GitHub Actions groups workflow runs together.
  ## github.workflow → The name of the workflow file.
  ## github.ref      → The branch or tag the workflow is running on.
  group: ${{ github.workflow }}-${{ github.ref }}
  ## If you push multiple times quickly, older runs would continue even though newer ones have started.
  ## Canceling previous runs reduces resource usage and speeds up feedback.
  cancel-in-progress: true

jobs:
  changelog_checker:
    name: A reviewer will let you know if it is required or can be bypassed
    runs-on: ubuntu-latest

    steps:
      - name: Check if towncrier change log entry is correct
        # if: steps.tests_changed.outputs.check_changelog == 'true'
        uses: scientific-python/action-towncrier-changelog@1d7332022f76e36fe8ce2d716b851f3f98063c62  # v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BOT_USERNAME: gilesbot  # 'astropy-bot'
