# Sync with .circleci/config.yml or project settings
#
# To enable this workflow on a fork, comment out:
#
# if: "${{ github.repository == 'scikit-plots/scikit-plots' }}"
---
name: CI Docs Preview Link Post CircleCI

on: # [status]  # [status, workflow_dispatch]
  workflow_dispatch: # Allows manual triggering of the workflow
  status:
    # branches: [ "main", "*.X" ]
    # types: [completed]  # ?
  # pull_request:
  #   types: [opened, synchronize, reopened]

## Top-level permissions (outside jobs)
## Job-level permissions (inside a specific job)
## Restrict the permissions granted to the use of secrets.GITHUB_TOKEN in this
## github actions workflow:
## https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions: read-all  # to fetch code (actions/checkout)
#  contents: read  # to fetch code (actions/checkout)

## Global environment variables (available to all jobs and steps)
## Job-level environment variables (override global, scoped to this job)
## Step-level environment variables (override job + global, scoped to this step)
env:
  ## Initially set IS_SKIP as false (you can set it to true here if you prefer a different default value)
  IS_SKIP: false  # ${{ env.IS_SKIP == 'false' }}
  ACTIONS_STEP_DEBUG: true  # optional but helps debug

jobs:
  circleci_artifacts_redirector_job:
    name: "CI Docs Preview Link Post CircleCI Artifact Redirector"
    runs-on: ubuntu-latest

    # To enable this workflow on a fork, comment out:
    # if: "github.repository == 'numpy/numpy' && !contains(github.event.head_commit.message, '[circle skip]') && !contains(github.event.head_commit.message, '[skip circle]')  && github.event.context == 'ci/circleci: build'"
    # Filter for CircleCI's build_docs, 'ci/circleci: build_docs' is the GitHub status check name set by CircleCI
    if: >-
      github.repository == 'scikit-plots/scikit-plots'
      && !contains(github.event.head_commit.message, '[circle skip]')
      && !contains(github.event.head_commit.message, '[skip circle]')
      && github.event.context == 'ci/circleci: build_docs'
      && github.event.state == 'success'

    permissions:
      contents: read
      statuses: write
      # issues: write
      # pull-requests: write  # needed to remove PR labels

    steps:
      # - name: Wait for CircleCI to finish
      #   run: sleep 120  # wait for build_docs to finish and upload artifacts
      # - name: Debug status
      #   run: |
      #     echo "Context: ${{ github.event.context }}"
      #     echo "State: ${{ github.event.state }}"

      - name: Redirect to Post CircleCI artifact link
        # uses: larsoner/circleci-artifacts-redirector-action@4e13a10d89177f4bfc8007a7064bdbeda848d8d1 # master
        uses: scientific-python/circleci-artifacts-redirector-action@7eafdb60666f57706a5525a2f5eb76224dc8779b # v1.1.0
        # if: ${{ env.IS_SKIP == 'false' }}  # Accessing IS_SKIP set earlier
        continue-on-error: true
        with:
          # api_token: ${{ env.CIRCLE_TOKEN }}
          api-token: ${{ secrets.CIRCLE_TOKEN }}  # Only if CircleCI project is private
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/docs/build/html/stable/index.html
          circleci-jobs: build_docs
          # → https://123-456.circle-artifacts.com/0/docs/build/html/stable/index.html
          job-title: 📘 Check the rendered Preview Docs here!

      # - name: Remove 'run-ci' label from PR
      #   uses: actions/github-script@v7
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       const prNumber = github.context.payload?.commit?.pull_requests?.[0]?.number;
      #       if (prNumber) {
      #         await github.rest.issues.removeLabel({
      #           owner: context.repo.owner,
      #           repo: context.repo.repo,
      #           issue_number: prNumber,
      #           name: 'run-ci'
      #         });
      #         console.log(`Removed 'run-ci' label from PR #${prNumber}`);
      #       } else {
      #         console.log("No PR number found for this commit.");
      #       }
