name: "Issue Labeler"

on:
  issues:
    types: [opened, edited]

# Restrict the permissions granted to the use of secrets.GITHUB_TOKEN in this
# github actions workflow:
# https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  contents: read  # Only read access to repository contents
  issues: write   # Full access to read and modify PRs (e.g., labels, comments)

jobs:
  label_issue:
    runs-on: ubuntu-latest

    steps:
      # label based on Issue title
      - name: label based on PR title
        uses: github/issue-labeler@c1b0f9f52a63158c4adc09425e858e87b32e9685 # v3.4
        if: github.repository == 'scikit-plots/scikit-plots'
        continue-on-error: true
        with:
          # repo-token: ${{ github.token }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          enable-versioned-regex: 0
          include-body: 0
          include-title: 1
          configuration-path: ".github/labeler-issue.yml"
