name: "Labeler Pull Request"

on:
  pull_request:  # Safer alternative to pull_request_target:
    types: [opened, edited]
    # branches:
    #   - main  # Only allow workflow to run on main branch PRs

# Restrict the permissions granted to the use of secrets.GITHUB_TOKEN in this
# github actions workflow:
# https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  contents: read
  issues: write
  pull-requests: read  # Avoid giving write access unless necessary

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
  # cancel-in-progress: false

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Grant write access only to this job

    steps:
      - name: "Debug: Check file existence"
        run: ls -lR .github/

      # label based on PR title
      - name: Labeler Issue
        uses: github/issue-labeler@c1b0f9f52a63158c4adc09425e858e87b32e9685 # v3.4
        if: github.repository == 'scikit-plots/scikit-plots'
        continue-on-error: true
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}  # ${{ github.token }}
          enable-versioned-regex: 0
          include-body: 0
          include-title: 1
          sync-labels: 1
          configuration-path: ".github/labeler.yml"

  labeler-by-glob:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Grant write access only to this job

    steps:
      - name: "Debug: Check file existence"
        run: ls -lR .github/

      # label based on glob files
      - name: Labeler Glob
        # uses: thomasjpfan/labeler@v2.5.1
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        if: github.repository == 'scikit-plots/scikit-plots'
        continue-on-error: true
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          # max-labels: "4"  # thomasjpfan
          configuration-path: ".github/labeler-by-glob.yml"

  pr-prefix-labeler:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Grant write access only to this job

    steps:
      - name: "Debug: Check file existence"
        run: ls -lR .github/

      - name: Labeler PR Prefix
        uses: gerrymanoim/pr-prefix-labeler@c8062327f6de59a9ae1c19f7f07cacd0b976b6fa # v3
        if: github.repository == 'scikit-plots/scikit-plots'
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: ".github/pr-prefix-labeler.yml"
