name: "Labeler Pull Request"

on:
  pull_request:  # Safer alternative to pull_request_target:
    types: [opened]
    # branches:
    #   - main  # Only allow workflow to run on main branch PRs

# Restrict the permissions granted to the use of secrets.GITHUB_TOKEN in this
# github actions workflow:
# https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  contents: read
  pull-requests: read  # Avoid giving write access unless necessary

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Grant write access only to this job

    steps:
    # label based on PR title
    - name: Label issue
      uses: github/issue-labeler@c1b0f9f52a63158c4adc09425e858e87b32e9685 # v3.4
      if: github.repository == 'scikit-plots/scikit-plots'
      continue-on-error: true
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        enable-versioned-regex: 0
        include-body: 0
        include-title: 1
        configuration-path: .github/labeler.yml

  labeler-by-glob:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Grant write access only to this job

    steps:
      # label based on glob files
      - name: Label glob
        # uses: thomasjpfan/labeler@v2.5.1
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        if: github.repository == 'scikit-plots/scikit-plots'
        continue-on-error: true
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          # max-labels: "4"  # thomasjpfan
          configuration-path: ".github/labeler-by-glob.yml"

  pr-prefix-labeler:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Grant write access only to this job

    steps:
      - name: Label PR prefix
        uses: gerrymanoim/pr-prefix-labeler@c8062327f6de59a9ae1c19f7f07cacd0b976b6fa # v3
        if: github.repository == 'scikit-plots/scikit-plots'
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
