name: "Pull Request Labeler"

on:
  # Use pull_request_target trigger if you're targeting a pull request from a fork:
  # pull_request:  Safer alternative to pull_request_target:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types: [opened, reopened, synchronize, edited]  # Triggers only on these events

# Restrict the permissions granted to the use of secrets.GITHUB_TOKEN in this
# github actions workflow:
# https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  contents: read        # Only read access to repository contents
  pull-requests: write  # Full access to read and modify PRs (e.g., labels, comments)

jobs:
  label_pull_request:
    runs-on: ubuntu-latest

    steps:
      # label based on PR glob files
      - name: label based on changed files
        # uses: thomasjpfan/labeler@v2.5.1
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        if: github.repository == 'scikit-plots/scikit-plots'
        continue-on-error: true
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          # max-labels: "4"  # thomasjpfan
          configuration-path: ".github/labeler.yml"  # ".github/labeler.yml"

      # label based on Issue title
      - name: label based on PR title
        uses: github/issue-labeler@c1b0f9f52a63158c4adc09425e858e87b32e9685 # v3.4
        if: github.repository == 'scikit-plots/scikit-plots'
        continue-on-error: true
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}  # ${{ github.token }}
          enable-versioned-regex: 0
          include-body: 0
          include-title: 1
          configuration-path: ".github/labeler-issue.yml"  # ".github/labeler.yml"

      # label based on PR Prefix
      - name: Labeler PR Prefix
        uses: gerrymanoim/pr-prefix-labeler@c8062327f6de59a9ae1c19f7f07cacd0b976b6fa # v3
        if: github.repository == 'scikit-plots/scikit-plots'
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: ".github/pr-prefix-labeler.yml"

      # label based on PR regex title
      #- name: Checkout (cloned) repository with full history
      #  uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      #  with:
      #    persist-credentials: false  # Prevents accidental credential exposure
      #    # submodules: true  # Fetch Hugo themes (true OR recursive)
      #    fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # - name: "Debug: Check file existence"
      #   run: ls -lR .github/

      # - name: Python Setup
      #   uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      #   with:
      #     python-version: '3.11'

      # - name: Install PyGithub
      #   run: |
      #     pip install -Uq PyGithub

      # - name: Label pull request
      #   run: python .github/scripts/label_title_regex.py
      #   env:
      #     CONTEXT_GITHUB: ${{ toJson(github) }}
