name: "Greetings"

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]  # Triggers only on these events
  issues:
    types:
    - opened
    - edited

# Restrict the permissions granted to the use of secrets.GITHUB_TOKEN in this
# github actions workflow:
# https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  contents: read        # Only read access to repository contents
  pull-requests: write  # Full access to read and modify PRs (e.g., labels, comments)
  issues: write         # Write access to issues (PRs are treated as issues)

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - name: 'Greet First-Time Contributors'
        uses: actions/first-interaction@34f15e814fe48ac9312ccf29db4e74fa767cbab7  # v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: >+
            Thank you for opening your first PR into scikit-plots👋!

            If you have not heard from us in a week or so, please leave a new
            comment below and that should bring it to our attention.
            Most of our reviewers are volunteers and sometimes things fall
            through the cracks.

            You can also join us:
              - [on github](https://github.com/orgs/scikit-plots/discussions)
              - [on gitter](https://gitter.im/scikit-plots/scikit-plots)
            for real-time discussion.

            For details on testing, writing docs, and our review process,
            please see [the developer
            guide](https://scikit-plots.github.io/dev/devel/index.html)

            We strive to be a welcoming and open project. Please follow our
            [Code of
            Conduct](https://scikit-plots.github.io/dev/project/code_of_conduct.html).
          issue-message: >+
            Thank you for opening your first Issue into scikit-plots👋!

            If you have not heard from us in a week or so, please leave a new
            comment below and that should bring it to our attention.
            Most of our reviewers are volunteers and sometimes things fall
            through the cracks.

            You can also join us:
              - [on github](https://github.com/orgs/scikit-plots/discussions)
              - [on gitter](https://gitter.im/scikit-plots/scikit-plots)
            for real-time discussion.

            For details on testing, writing docs, and our review process,
            please see [the developer
            guide](https://scikit-plots.github.io/dev/devel/index.html)

            We strive to be a welcoming and open project. Please follow our
            [Code of
            Conduct](https://scikit-plots.github.io/dev/project/code_of_conduct.html).

            GitHub issues in the scikit-plots repository are used to track bug
            reports and feature requests; If your issue poses a question about
            how to use scikit-plots, please instead raise your question in the
            [on github](https://github.com/orgs/scikit-plots/discussions) and close
            this issue.

      - name: 'Comment Draft PR'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea  # v7.0.1
        if: github.event.pull_request.draft == true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thank you for your draft pull request!
              Do you know that you can use `[ci skip]` or `[skip ci]` in your commit messages to skip running continuous integration tests until you are ready?'
            })
